//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class gpu
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }

        [Required]
        [StringLength(20)]
        [RegularExpression(@"^[^,:*?""<>\|]*$")]
        public string vram { get; set; }

        [Required]
        [StringLength(20)]
        [RegularExpression(@"^[^,:*?""<>\|]*$")]
        public string chipset { get; set; }

        [Required]
        [StringLength(20)]
        [RegularExpression(@"^[^,:*?""<>\|]*$")]
        public string resolution { get; set; }
    
        public virtual product product { get; set; }
    }
}
