//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class hardDisc
    {
        public int id { get; set; }
        public int productId { get; set; }
        public string type { get; set; }
        public string capacity { get; set; }
        public string connector { get; set; }
        public string frequency { get; set; }
    
        public virtual product product { get; set; }
    }
}
