//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int Id { get; set; }
        public int userId { get; set; }
        public Nullable<int> productId { get; set; }
        public int quantity { get; set; }
        public Nullable<int> desktopID { get; set; }
    
        public virtual Desktop Desktop { get; set; }
        public virtual product product { get; set; }
        public virtual User User { get; set; }
    }
}
