//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cpu
    {
        public int id { get; set; }
        public int productId { get; set; }

        [Required]
        [RegularExpression(@"^[^,:*?""<>\|]*$")]
        public Nullable<int> cores { get; set; }

        [Required]
        [RegularExpression(@"^[^,:*?""<>\|]*$")]
        public Nullable<int> threads { get; set; }

        [Required]
        [StringLength(50)]
        [RegularExpression(@"^[^,:*?""<>\|]*$")]
        public string model { get; set; }

        [Required]
        [StringLength(20)]
        [RegularExpression(@"^[^,:*?""<>\|]*$")]
        public string frequency { get; set; }

        [Required]
        [StringLength(20)]
        [RegularExpression(@"^[^,:*?""<>\|]*$")]
        public string chipset { get; set; }

        [Required]
        [StringLength(20)]
        [RegularExpression(@"^[^,:*?""<>\|]*$")]
        public string socket { get; set; }
    
        public virtual product product { get; set; }
    }
}
