//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eshop
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int orderId { get; set; }
        public Nullable<int> productId { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
        public int id { get; set; }
        public Nullable<int> desktopId { get; set; }
    
        public virtual Desktop Desktop { get; set; }
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
